// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: carrier.proto

package carrierpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_KIND_UNSPECIFIED Kind = 0
	Kind_KIND_HELLO       Kind = 1
	Kind_KIND_READY       Kind = 2
	Kind_KIND_DATA        Kind = 3
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_HELLO",
		2: "KIND_READY",
		3: "KIND_DATA",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_HELLO":       1,
		"KIND_READY":       2,
		"KIND_DATA":        3,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_carrier_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_carrier_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_carrier_proto_rawDescGZIP(), []int{0}
}

// The relay carries opaque inner TLS, never a caller-specified destination.
type Frame struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Version     uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Kind        Kind                   `protobuf:"varint,2,opt,name=kind,proto3,enum=portico.carrier.v1.Kind" json:"kind,omitempty"`
	ConnectorId string                 `protobuf:"bytes,3,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	Data        []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// Correlates a single authenticated data RPC with its cancellation watch.
	// It is not a bearer credential or a resource/destination identifier.
	StreamId      []byte `protobuf:"bytes,5,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_carrier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_carrier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_carrier_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Frame) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *Frame) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *Frame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Frame) GetStreamId() []byte {
	if x != nil {
		return x.StreamId
	}
	return nil
}

var File_carrier_proto protoreflect.FileDescriptor

const file_carrier_proto_rawDesc = "" +
	"\n" +
	"\rcarrier.proto\x12\x12portico.carrier.v1\"\xa3\x01\n" +
	"\x05Frame\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12,\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x18.portico.carrier.v1.KindR\x04kind\x12!\n" +
	"\fconnector_id\x18\x03 \x01(\tR\vconnectorId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1b\n" +
	"\tstream_id\x18\x05 \x01(\fR\bstreamId*K\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"KIND_HELLO\x10\x01\x12\x0e\n" +
	"\n" +
	"KIND_READY\x10\x02\x12\r\n" +
	"\tKIND_DATA\x10\x032\xce\x01\n" +
	"\aCarrier\x12@\n" +
	"\x04Dial\x12\x19.portico.carrier.v1.Frame\x1a\x19.portico.carrier.v1.Frame(\x010\x01\x12@\n" +
	"\x04Bind\x12\x19.portico.carrier.v1.Frame\x1a\x19.portico.carrier.v1.Frame(\x010\x01\x12?\n" +
	"\x05Watch\x12\x19.portico.carrier.v1.Frame\x1a\x19.portico.carrier.v1.Frame0\x01B*Z(portico.local/portico/internal/carrierpbb\x06proto3"

var (
	file_carrier_proto_rawDescOnce sync.Once
	file_carrier_proto_rawDescData []byte
)

func file_carrier_proto_rawDescGZIP() []byte {
	file_carrier_proto_rawDescOnce.Do(func() {
		file_carrier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carrier_proto_rawDesc), len(file_carrier_proto_rawDesc)))
	})
	return file_carrier_proto_rawDescData
}

var file_carrier_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_carrier_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_carrier_proto_goTypes = []any{
	(Kind)(0),     // 0: portico.carrier.v1.Kind
	(*Frame)(nil), // 1: portico.carrier.v1.Frame
}
var file_carrier_proto_depIdxs = []int32{
	0, // 0: portico.carrier.v1.Frame.kind:type_name -> portico.carrier.v1.Kind
	1, // 1: portico.carrier.v1.Carrier.Dial:input_type -> portico.carrier.v1.Frame
	1, // 2: portico.carrier.v1.Carrier.Bind:input_type -> portico.carrier.v1.Frame
	1, // 3: portico.carrier.v1.Carrier.Watch:input_type -> portico.carrier.v1.Frame
	1, // 4: portico.carrier.v1.Carrier.Dial:output_type -> portico.carrier.v1.Frame
	1, // 5: portico.carrier.v1.Carrier.Bind:output_type -> portico.carrier.v1.Frame
	1, // 6: portico.carrier.v1.Carrier.Watch:output_type -> portico.carrier.v1.Frame
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_carrier_proto_init() }
func file_carrier_proto_init() {
	if File_carrier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carrier_proto_rawDesc), len(file_carrier_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_carrier_proto_goTypes,
		DependencyIndexes: file_carrier_proto_depIdxs,
		EnumInfos:         file_carrier_proto_enumTypes,
		MessageInfos:      file_carrier_proto_msgTypes,
	}.Build()
	File_carrier_proto = out.File
	file_carrier_proto_goTypes = nil
	file_carrier_proto_depIdxs = nil
}
