// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: carrier.proto

package carrierpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Carrier_Dial_FullMethodName  = "/portico.carrier.v1.Carrier/Dial"
	Carrier_Bind_FullMethodName  = "/portico.carrier.v1.Carrier/Bind"
	Carrier_Watch_FullMethodName = "/portico.carrier.v1.Carrier/Watch"
)

// CarrierClient is the client API for Carrier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CarrierClient interface {
	Dial(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error)
	Bind(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error)
	// A separate flow-control window keeps cancellation out of unread payload.
	// The only response is READY; any end closes the data RPC.
	Watch(ctx context.Context, in *Frame, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Frame], error)
}

type carrierClient struct {
	cc grpc.ClientConnInterface
}

func NewCarrierClient(cc grpc.ClientConnInterface) CarrierClient {
	return &carrierClient{cc}
}

func (c *carrierClient) Dial(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Carrier_ServiceDesc.Streams[0], Carrier_Dial_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Frame, Frame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Carrier_DialClient = grpc.BidiStreamingClient[Frame, Frame]

func (c *carrierClient) Bind(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Carrier_ServiceDesc.Streams[1], Carrier_Bind_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Frame, Frame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Carrier_BindClient = grpc.BidiStreamingClient[Frame, Frame]

func (c *carrierClient) Watch(ctx context.Context, in *Frame, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Carrier_ServiceDesc.Streams[2], Carrier_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Frame, Frame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Carrier_WatchClient = grpc.ServerStreamingClient[Frame]

// CarrierServer is the server API for Carrier service.
// All implementations must embed UnimplementedCarrierServer
// for forward compatibility.
type CarrierServer interface {
	Dial(grpc.BidiStreamingServer[Frame, Frame]) error
	Bind(grpc.BidiStreamingServer[Frame, Frame]) error
	// A separate flow-control window keeps cancellation out of unread payload.
	// The only response is READY; any end closes the data RPC.
	Watch(*Frame, grpc.ServerStreamingServer[Frame]) error
	mustEmbedUnimplementedCarrierServer()
}

// UnimplementedCarrierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCarrierServer struct{}

func (UnimplementedCarrierServer) Dial(grpc.BidiStreamingServer[Frame, Frame]) error {
	return status.Error(codes.Unimplemented, "method Dial not implemented")
}
func (UnimplementedCarrierServer) Bind(grpc.BidiStreamingServer[Frame, Frame]) error {
	return status.Error(codes.Unimplemented, "method Bind not implemented")
}
func (UnimplementedCarrierServer) Watch(*Frame, grpc.ServerStreamingServer[Frame]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedCarrierServer) mustEmbedUnimplementedCarrierServer() {}
func (UnimplementedCarrierServer) testEmbeddedByValue()                 {}

// UnsafeCarrierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CarrierServer will
// result in compilation errors.
type UnsafeCarrierServer interface {
	mustEmbedUnimplementedCarrierServer()
}

func RegisterCarrierServer(s grpc.ServiceRegistrar, srv CarrierServer) {
	// If the following call panics, it indicates UnimplementedCarrierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Carrier_ServiceDesc, srv)
}

func _Carrier_Dial_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CarrierServer).Dial(&grpc.GenericServerStream[Frame, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Carrier_DialServer = grpc.BidiStreamingServer[Frame, Frame]

func _Carrier_Bind_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CarrierServer).Bind(&grpc.GenericServerStream[Frame, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Carrier_BindServer = grpc.BidiStreamingServer[Frame, Frame]

func _Carrier_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Frame)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CarrierServer).Watch(m, &grpc.GenericServerStream[Frame, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Carrier_WatchServer = grpc.ServerStreamingServer[Frame]

// Carrier_ServiceDesc is the grpc.ServiceDesc for Carrier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Carrier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "portico.carrier.v1.Carrier",
	HandlerType: (*CarrierServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Dial",
			Handler:       _Carrier_Dial_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Bind",
			Handler:       _Carrier_Bind_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _Carrier_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "carrier.proto",
}
